/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Denis Imeri
 */
public class DateTimeFormatterGUI extends javax.swing.JFrame {

    /**
     * Creates new form DateTimeFormatterUI
     */
    public DateTimeFormatterGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        paCheck = new javax.swing.JPanel();
        cbDatum = new javax.swing.JCheckBox();
        cbTime = new javax.swing.JCheckBox();
        paInput = new javax.swing.JPanel();
        lbTag = new javax.swing.JLabel();
        tfTag = new javax.swing.JTextField();
        lbMonat = new javax.swing.JLabel();
        tfMonat = new javax.swing.JTextField();
        lbJahr = new javax.swing.JLabel();
        tfJahr = new javax.swing.JTextField();
        lbStunde = new javax.swing.JLabel();
        tfStunde = new javax.swing.JTextField();
        lbMinute = new javax.swing.JLabel();
        tfMinute = new javax.swing.JTextField();
        paFormat = new javax.swing.JPanel();
        btFormat = new javax.swing.JButton();
        tfDateOut = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paCheck.setBorder(javax.swing.BorderFactory.createTitledBorder("Ausgabe"));
        paCheck.setLayout(new java.awt.GridLayout());

        cbDatum.setText("Datum");
        paCheck.add(cbDatum);

        cbTime.setText("Uhrzeit");
        paCheck.add(cbTime);

        getContentPane().add(paCheck, java.awt.BorderLayout.PAGE_START);

        paInput.setBorder(javax.swing.BorderFactory.createTitledBorder("Eingabewerte"));
        paInput.setLayout(new java.awt.GridLayout(5, 2));

        lbTag.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTag.setText("Tag: ");
        paInput.add(lbTag);

        tfTag.setText("1");
        paInput.add(tfTag);

        lbMonat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMonat.setText("Monat: ");
        paInput.add(lbMonat);

        tfMonat.setText("12");
        paInput.add(tfMonat);

        lbJahr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbJahr.setText("Jahr: ");
        paInput.add(lbJahr);

        tfJahr.setText("2018");
        paInput.add(tfJahr);

        lbStunde.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbStunde.setText("Stunde: ");
        paInput.add(lbStunde);

        tfStunde.setText("13");
        tfStunde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStundeActionPerformed(evt);
            }
        });
        paInput.add(tfStunde);

        lbMinute.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMinute.setText("Minute: ");
        paInput.add(lbMinute);

        tfMinute.setText("42");
        paInput.add(tfMinute);

        getContentPane().add(paInput, java.awt.BorderLayout.CENTER);

        paFormat.setLayout(new java.awt.GridBagLayout());

        btFormat.setText("formatieren");
        btFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFormat(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        paFormat.add(btFormat, gridBagConstraints);

        tfDateOut.setEditable(false);
        tfDateOut.setColumns(20);
        tfDateOut.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfDateOut.setText("01.12.2018 - 13:42");
        paFormat.add(tfDateOut, new java.awt.GridBagConstraints());

        getContentPane().add(paFormat, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfStundeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStundeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStundeActionPerformed

    private void onFormat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onFormat
        int[] values;
        String type, text = "";
        boolean ok = true;
        if(cbDatum.isSelected() && cbTime.isSelected()){
            try{
                values = new int[5];
                values[0] = Integer.parseInt(tfTag.getText());
                values[1] = Integer.parseInt(tfMonat.getText());
                values[2] = Integer.parseInt(tfJahr.getText());
                values[3] = Integer.parseInt(tfStunde.getText());
                values[4] = Integer.parseInt(tfMinute.getText());
                if(!DateTimeFormatter.isIn(1, values[0], 31)) ok = false;
                if(!DateTimeFormatter.isIn(1, values[1], 12)) ok = false;
                if(!DateTimeFormatter.isIn(1, values[3], 24)) ok = false;
                if(!DateTimeFormatter.isIn(1, values[4], 60)) ok = false;
                type = "DT";
                if(ok){
                    text = DateTimeFormatter.format(type, values);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Falsche Werte");
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Es sind leere oder Felder mit Buchstaben vorhanden");
            }
        }
        else if(cbDatum.isSelected()){
            try{
                values = new int[3];
                values[0] = Integer.parseInt(tfTag.getText());
                values[1] = Integer.parseInt(tfMonat.getText());
                values[2] = Integer.parseInt(tfJahr.getText());
                if(!DateTimeFormatter.isIn(1, values[0], 31)) ok = false;
                if(!DateTimeFormatter.isIn(1, values[1], 12)) ok = false;
                type = "D";
                if(ok){
                    text = DateTimeFormatter.format(type, values);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Falsche Werte");
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Es sind leere oder Felder mit Buchstaben vorhanden");
            }
        }
        else if(cbTime.isSelected()){
            try{
                values = new int[2];
                values[0] = Integer.parseInt(tfStunde.getText());
                values[1] = Integer.parseInt(tfMinute.getText());
                if(!DateTimeFormatter.isIn(1, values[0], 24)) ok = false;
                if(!DateTimeFormatter.isIn(1, values[1], 60)) ok = false;
                type = "T";
                if(ok){
                    text = DateTimeFormatter.format(type, values);
                }
                else{
                    text = "Falsche Wert(e)";
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Es sind leere oder Felder mit Buchstaben vorhanden");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Du hast nichts ausgewählt");
        }
        tfDateOut.setText(text);
    }//GEN-LAST:event_onFormat

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DateTimeFormatterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DateTimeFormatterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DateTimeFormatterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DateTimeFormatterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DateTimeFormatterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFormat;
    private javax.swing.JCheckBox cbDatum;
    private javax.swing.JCheckBox cbTime;
    private javax.swing.JLabel lbJahr;
    private javax.swing.JLabel lbMinute;
    private javax.swing.JLabel lbMonat;
    private javax.swing.JLabel lbStunde;
    private javax.swing.JLabel lbTag;
    private javax.swing.JPanel paCheck;
    private javax.swing.JPanel paFormat;
    private javax.swing.JPanel paInput;
    private javax.swing.JTextField tfDateOut;
    private javax.swing.JTextField tfJahr;
    private javax.swing.JTextField tfMinute;
    private javax.swing.JTextField tfMonat;
    private javax.swing.JTextField tfStunde;
    private javax.swing.JTextField tfTag;
    // End of variables declaration//GEN-END:variables
}
