/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.CurrencyConverter;

/**
 *
 * @author Denis Imeri
 */
public class CurrencyGUI extends javax.swing.JFrame {

    /**
     * Creates new form CurrencyGUI
     */
    public CurrencyGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbEuro = new javax.swing.JLabel();
        tfEuro = new javax.swing.JTextField();
        lbDollar = new javax.swing.JLabel();
        tfDollar = new javax.swing.JTextField();
        btEuroDollar = new javax.swing.JButton();
        btDollarEuro = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(250, 180));
        getContentPane().setLayout(new java.awt.GridLayout(3, 2));

        lbEuro.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 18)); // NOI18N
        lbEuro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEuro.setText("Euro (€) ");
        lbEuro.setPreferredSize(new java.awt.Dimension(100, 60));
        getContentPane().add(lbEuro);

        tfEuro.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 18)); // NOI18N
        tfEuro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfEuro.setText("0,0");
        tfEuro.setPreferredSize(new java.awt.Dimension(100, 60));
        getContentPane().add(tfEuro);

        lbDollar.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 18)); // NOI18N
        lbDollar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDollar.setText("Dollar($) ");
        lbDollar.setPreferredSize(new java.awt.Dimension(100, 60));
        getContentPane().add(lbDollar);

        tfDollar.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 18)); // NOI18N
        tfDollar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDollar.setText("0,0");
        tfDollar.setPreferredSize(new java.awt.Dimension(100, 60));
        getContentPane().add(tfDollar);

        btEuroDollar.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 18)); // NOI18N
        btEuroDollar.setText("€ --> $");
        btEuroDollar.setPreferredSize(new java.awt.Dimension(100, 60));
        btEuroDollar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euroToDollar(evt);
            }
        });
        getContentPane().add(btEuroDollar);

        btDollarEuro.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 18)); // NOI18N
        btDollarEuro.setText("$ --> €");
        btDollarEuro.setPreferredSize(new java.awt.Dimension(100, 60));
        btDollarEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dollarToEuro(evt);
            }
        });
        getContentPane().add(btDollarEuro);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void euroToDollar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euroToDollar
        String textEuro = tfEuro.getText().replace(',', '.');
        double euro = Double.parseDouble(textEuro);
        double dollar = CurrencyConverter.euroToDollar(euro);
        String textRes = String.format("%.2f", dollar);
        tfDollar.setText(textRes);
    }//GEN-LAST:event_euroToDollar

    private void dollarToEuro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dollarToEuro
        String textDollar = tfDollar.getText().replace(',', '.');
        double dollar = Double.parseDouble(textDollar);
        double euro = CurrencyConverter.euroToDollar(dollar);
        String textRes = String.format("%.2f", euro);
        tfDollar.setText(textRes);
    }//GEN-LAST:event_dollarToEuro

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDollarEuro;
    private javax.swing.JButton btEuroDollar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbDollar;
    private javax.swing.JLabel lbEuro;
    private javax.swing.JTextField tfDollar;
    private javax.swing.JTextField tfEuro;
    // End of variables declaration//GEN-END:variables
}
