/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Song;
import bl.SongModel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Denis Imeri
 */
public class PlayListGUI extends javax.swing.JFrame {
    
    private SongModel allSongs = new SongModel();
    private SongModel playlist = new SongModel();

    /**
     * Creates new form PlayListGUI
     */
    public PlayListGUI() {
        initComponents();
        liSongs.setModel(allSongs);
        allSongs.getPlaylistData();
        liPlaylist.setModel(playlist);
        int allLength = allSongs.getCompleteLength();
        lbSongs.setText(String.format("Spielzeit: %02d:%02d", allLength/60, allLength%6));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu = new javax.swing.JPopupMenu();
        popFilter = new javax.swing.JMenu();
        miTitel = new javax.swing.JMenuItem();
        miLaenge = new javax.swing.JMenuItem();
        miInterpret = new javax.swing.JMenuItem();
        spTop = new javax.swing.JScrollPane();
        liSongs = new javax.swing.JList<>();
        paButtons = new javax.swing.JPanel();
        btAdd = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        lbSongs = new javax.swing.JLabel();
        spPlaylist = new javax.swing.JScrollPane();
        liPlaylist = new javax.swing.JList<>();
        lbPlaylist = new javax.swing.JLabel();

        popFilter.setText("sortieren nach");
        popFilter.setActionCommand("");

        miTitel.setText("Titel");
        miTitel.setActionCommand("titel");
        miTitel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSort(evt);
            }
        });
        popFilter.add(miTitel);

        miLaenge.setText("Laenge");
        miLaenge.setActionCommand("laenge");
        miLaenge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSort(evt);
            }
        });
        popFilter.add(miLaenge);

        popMenu.add(popFilter);

        miInterpret.setText("filtern nach Interpret");
        miInterpret.setActionCommand("interpret");
        miInterpret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFilter(evt);
            }
        });
        popMenu.add(miInterpret);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new java.awt.GridLayout(4, 1));

        liSongs.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 12)); // NOI18N
        spTop.setViewportView(liSongs);

        getContentPane().add(spTop);

        paButtons.setLayout(new java.awt.GridLayout(1, 0));

        btAdd.setText("Hinzufügen \\/");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAddSong(evt);
            }
        });
        paButtons.add(btAdd);

        btDelete.setText("Löschen /\\");
            btDelete.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    onRemoveSong(evt);
                }
            });
            paButtons.add(btDelete);

            lbSongs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lbSongs.setText("Spielzeit: ");
            paButtons.add(lbSongs);

            getContentPane().add(paButtons);

            liPlaylist.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 12)); // NOI18N
            spPlaylist.setViewportView(liPlaylist);

            getContentPane().add(spPlaylist);

            lbPlaylist.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            lbPlaylist.setText("Spielzeit: 00:00 ");
            getContentPane().add(lbPlaylist);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void onAddSong(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAddSong
        List<Song> toAdd = liSongs.getSelectedValuesList();
        
        playlist.addSongs(toAdd);
        int length = playlist.getCompleteLength();
        lbPlaylist.setText(String.format("Spielzeit: %02d:%02d ", length/60, length%60));
    }//GEN-LAST:event_onAddSong

    private void onRemoveSong(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRemoveSong
        List<Song> toRemove = liPlaylist.getSelectedValuesList();
        playlist.removeSongs(toRemove);
        int length = playlist.getCompleteLength();
        lbPlaylist.setText(String.format("Spielzeit: %02d:%02d ", length/60, length%60));
    }//GEN-LAST:event_onRemoveSong

    private void onSort(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSort
        String type = evt.getActionCommand();
        allSongs.sort(type);
    }//GEN-LAST:event_onSort

    private void onFilter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onFilter
        String filter = JOptionPane.showInputDialog("Interpret eingeben, leere Eingabe falls alle angezeigt werden sollen");
        allSongs.filter(filter);
    }//GEN-LAST:event_onFilter

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayListGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDelete;
    private javax.swing.JLabel lbPlaylist;
    private javax.swing.JLabel lbSongs;
    private javax.swing.JList<Song> liPlaylist;
    private javax.swing.JList<Song> liSongs;
    private javax.swing.JMenuItem miInterpret;
    private javax.swing.JMenuItem miLaenge;
    private javax.swing.JMenuItem miTitel;
    private javax.swing.JPanel paButtons;
    private javax.swing.JMenu popFilter;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JScrollPane spPlaylist;
    private javax.swing.JScrollPane spTop;
    // End of variables declaration//GEN-END:variables
}
