/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Animal;
import beans.AnimalIO;
import bl.AnimalListModel;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Denis Imeri
 */
public class AnimalGUI extends javax.swing.JFrame {

    private AnimalListModel alm;

    /**
     * Creates new form AnimalGUI
     */
    public AnimalGUI() {
        initComponents();
        
        try {
            alm = new AnimalListModel(AnimalIO.loadAnimals());
            liAnimals.setModel(alm);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "IO-error - "+ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        miAll = new javax.swing.JMenuItem();
        miSpider = new javax.swing.JMenuItem();
        miCats = new javax.swing.JMenuItem();
        btAction = new javax.swing.JButton();
        spList = new javax.swing.JScrollPane();
        liAnimals = new javax.swing.JList<>();

        miAll.setText("None");
        miAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFilter(evt);
            }
        });
        jPopupMenu1.add(miAll);

        miSpider.setText("Spider");
        miSpider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFilter(evt);
            }
        });
        jPopupMenu1.add(miSpider);

        miCats.setText("Cat");
        miCats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFilter(evt);
            }
        });
        jPopupMenu1.add(miCats);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onCloseWindow(evt);
            }
        });

        btAction.setText("Action");
        btAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAction(evt);
            }
        });
        getContentPane().add(btAction, java.awt.BorderLayout.PAGE_END);

        liAnimals.setComponentPopupMenu(jPopupMenu1);
        spList.setViewportView(liAnimals);

        getContentPane().add(spList, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAction
        /*alm.addAnimal(new Animal("Dog", "Husky", 5));
        int index = liAnimals.getSelectedIndex();
        if (index != -1) {
            alm.removeAnimal(index);
        }*/
        List<Animal> toDelete = liAnimals.getSelectedValuesList();
        alm.removeAnimals(toDelete);
        
    }//GEN-LAST:event_onAction

    private void onFilter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onFilter
        System.out.println(evt.getActionCommand());
        alm.filter(evt.getActionCommand());
        
    }//GEN-LAST:event_onFilter

    private void onCloseWindow(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onCloseWindow
        try {
            AnimalIO.saveAnimals(alm.getAllAnimals());
        } catch (IOException ex) {
            Logger.getLogger(AnimalGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_onCloseWindow
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAction;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JList<Animal> liAnimals;
    private javax.swing.JMenuItem miAll;
    private javax.swing.JMenuItem miCats;
    private javax.swing.JMenuItem miSpider;
    private javax.swing.JScrollPane spList;
    // End of variables declaration//GEN-END:variables
}
