/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.Fraction;

/**
 *
 * @author Denis Imeri
 */
public class FractionGUI extends javax.swing.JFrame {

    /**
     * Creates new form FractionGUI
     */
    public FractionGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        paEingabe = new javax.swing.JPanel();
        lbNenner = new javax.swing.JLabel();
        lbLine = new javax.swing.JLabel();
        tfNumInp = new javax.swing.JTextField();
        tfDenInp = new javax.swing.JTextField();
        btCalc = new javax.swing.JButton();
        paAusgabe = new javax.swing.JPanel();
        lbNenner1 = new javax.swing.JLabel();
        lbLine1 = new javax.swing.JLabel();
        tfNumOut = new javax.swing.JTextField();
        tfDenOut = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 400));

        paEingabe.setBorder(javax.swing.BorderFactory.createTitledBorder("Eingabe"));
        paEingabe.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        paEingabe.setLayout(new java.awt.GridBagLayout());

        lbNenner.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbNenner.setText("Bruch: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 11, 0, 10);
        paEingabe.add(lbNenner, gridBagConstraints);

        lbLine.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbLine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLine.setText("-----------------");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 5, 0);
        paEingabe.add(lbLine, gridBagConstraints);

        tfNumInp.setColumns(8);
        tfNumInp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfNumInp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNumInp.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        paEingabe.add(tfNumInp, gridBagConstraints);

        tfDenInp.setColumns(8);
        tfDenInp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfDenInp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDenInp.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        paEingabe.add(tfDenInp, gridBagConstraints);

        getContentPane().add(paEingabe, java.awt.BorderLayout.PAGE_START);

        btCalc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btCalc.setText("jButton1");
        btCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCalculate(evt);
            }
        });
        getContentPane().add(btCalc, java.awt.BorderLayout.CENTER);

        paAusgabe.setBorder(javax.swing.BorderFactory.createTitledBorder("gekürzt"));
        paAusgabe.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        paAusgabe.setLayout(new java.awt.GridBagLayout());

        lbNenner1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbNenner1.setText("Bruch: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 11, 0, 10);
        paAusgabe.add(lbNenner1, gridBagConstraints);

        lbLine1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbLine1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLine1.setText("-----------------");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 5, 0);
        paAusgabe.add(lbLine1, gridBagConstraints);

        tfNumOut.setEditable(false);
        tfNumOut.setColumns(8);
        tfNumOut.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfNumOut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNumOut.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        paAusgabe.add(tfNumOut, gridBagConstraints);

        tfDenOut.setEditable(false);
        tfDenOut.setColumns(8);
        tfDenOut.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfDenOut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDenOut.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        paAusgabe.add(tfDenOut, gridBagConstraints);

        getContentPane().add(paAusgabe, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void onCalculate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCalculate
        int num = Integer.parseInt(tfNumInp.getText());
        int den = Integer.parseInt(tfDenInp.getText());
        Fraction fr = new Fraction(num, den);
        fr.cancel();
        int numOut = fr.getNumerator();
        int denOut = fr.getDenominator();
        tfNumOut.setText(String.format("%d", numOut));
        tfDenOut.setText(String.format("%d", denOut));
    }//GEN-LAST:event_onCalculate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FractionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FractionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FractionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FractionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FractionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalc;
    private javax.swing.JLabel lbLine;
    private javax.swing.JLabel lbLine1;
    private javax.swing.JLabel lbNenner;
    private javax.swing.JLabel lbNenner1;
    private javax.swing.JPanel paAusgabe;
    private javax.swing.JPanel paEingabe;
    private javax.swing.JTextField tfDenInp;
    private javax.swing.JTextField tfDenOut;
    private javax.swing.JTextField tfNumInp;
    private javax.swing.JTextField tfNumOut;
    // End of variables declaration//GEN-END:variables
}
