/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Denis Imeri
 */
public class FractionFrameGUI extends javax.swing.JFrame {

    /**
     * Creates new form FractionFrameGUI
     */
    public FractionFrameGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        paEingabe = new javax.swing.JPanel();
        lbNenner = new javax.swing.JLabel();
        lbLine = new javax.swing.JLabel();
        tfNumerator = new javax.swing.JTextField();
        tfDenominator = new javax.swing.JTextField();
        btCalculate = new javax.swing.JButton();
        paAusgabe = new javax.swing.JPanel();
        lbNenner1 = new javax.swing.JLabel();
        lbLine1 = new javax.swing.JLabel();
        tfNumerator1 = new javax.swing.JTextField();
        tfDenominator1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paEingabe.setBorder(javax.swing.BorderFactory.createTitledBorder("Eingabe"));
        paEingabe.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        paEingabe.setLayout(new java.awt.GridBagLayout());

        lbNenner.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbNenner.setText("Bruch: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 11, 0, 10);
        paEingabe.add(lbNenner, gridBagConstraints);

        lbLine.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbLine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLine.setText("-----------------");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 5, 0);
        paEingabe.add(lbLine, gridBagConstraints);

        tfNumerator.setColumns(6);
        tfNumerator.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfNumerator.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNumerator.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        paEingabe.add(tfNumerator, gridBagConstraints);

        tfDenominator.setColumns(6);
        tfDenominator.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfDenominator.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDenominator.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        paEingabe.add(tfDenominator, gridBagConstraints);

        getContentPane().add(paEingabe, java.awt.BorderLayout.PAGE_START);

        btCalculate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btCalculate.setText("jButton1");
        getContentPane().add(btCalculate, java.awt.BorderLayout.CENTER);

        paAusgabe.setBorder(javax.swing.BorderFactory.createTitledBorder("gekürzt"));
        paAusgabe.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        paAusgabe.setLayout(new java.awt.GridBagLayout());

        lbNenner1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbNenner1.setText("Bruch: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 11, 0, 10);
        paAusgabe.add(lbNenner1, gridBagConstraints);

        lbLine1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbLine1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLine1.setText("-----------------");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 5, 0);
        paAusgabe.add(lbLine1, gridBagConstraints);

        tfNumerator1.setEditable(false);
        tfNumerator1.setColumns(6);
        tfNumerator1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfNumerator1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNumerator1.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        paAusgabe.add(tfNumerator1, gridBagConstraints);

        tfDenominator1.setEditable(false);
        tfDenominator1.setColumns(6);
        tfDenominator1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tfDenominator1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDenominator1.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        paAusgabe.add(tfDenominator1, gridBagConstraints);

        getContentPane().add(paAusgabe, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FractionFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FractionFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FractionFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FractionFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FractionFrameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalculate;
    private javax.swing.JLabel lbLine;
    private javax.swing.JLabel lbLine1;
    private javax.swing.JLabel lbNenner;
    private javax.swing.JLabel lbNenner1;
    private javax.swing.JPanel paAusgabe;
    private javax.swing.JPanel paEingabe;
    private javax.swing.JTextField tfDenominator;
    private javax.swing.JTextField tfDenominator1;
    private javax.swing.JTextField tfNumerator;
    private javax.swing.JTextField tfNumerator1;
    // End of variables declaration//GEN-END:variables
}
