/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.SumUpBL;

/**
 *
 * @author Denis Imeri
 */
public class SumUpGUI extends javax.swing.JFrame {

    /**
     * Creates new form sumUpGui
     */
    public SumUpGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCalculate = new javax.swing.JButton();
        paCenter = new javax.swing.JPanel();
        lbStart = new javax.swing.JLabel();
        tfStart = new javax.swing.JTextField();
        lbEnd = new javax.swing.JLabel();
        tfEnd = new javax.swing.JTextField();
        lbSum = new javax.swing.JLabel();
        tfSum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sum UP GUI");

        btCalculate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btCalculate.setText("Calculate");
        btCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCalculate(evt);
            }
        });
        getContentPane().add(btCalculate, java.awt.BorderLayout.SOUTH);

        paCenter.setLayout(new java.awt.GridLayout(3, 3, 4, 5));

        lbStart.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 24)); // NOI18N
        lbStart.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbStart.setText("Start-number:");
        paCenter.add(lbStart);

        tfStart.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 24)); // NOI18N
        tfStart.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfStart.setText("3");
        tfStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStartActionPerformed(evt);
            }
        });
        paCenter.add(tfStart);

        lbEnd.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 24)); // NOI18N
        lbEnd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEnd.setText("End-number:");
        paCenter.add(lbEnd);

        tfEnd.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 24)); // NOI18N
        tfEnd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfEnd.setText("5");
        paCenter.add(tfEnd);

        lbSum.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 24)); // NOI18N
        lbSum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbSum.setText("Sum");
        paCenter.add(lbSum);

        tfSum.setEditable(false);
        tfSum.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 24)); // NOI18N
        tfSum.setForeground(new java.awt.Color(255, 0, 0));
        tfSum.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfSum.setText("0");
        paCenter.add(tfSum);

        getContentPane().add(paCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onCalculate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCalculate
        int startNum = Integer.parseInt(tfStart.getText());
        int endNum = Integer.parseInt(tfEnd.getText());
        
        SumUpBL bl = new SumUpBL(startNum, endNum);
        bl.calculate();
        int res = bl.getSum();
        
        tfSum.setText(res+"");
    }//GEN-LAST:event_onCalculate

    private void tfStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SumUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SumUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SumUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SumUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SumUpGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalculate;
    private javax.swing.JLabel lbEnd;
    private javax.swing.JLabel lbStart;
    private javax.swing.JLabel lbSum;
    private javax.swing.JPanel paCenter;
    private javax.swing.JTextField tfEnd;
    private javax.swing.JTextField tfStart;
    private javax.swing.JTextField tfSum;
    // End of variables declaration//GEN-END:variables
}
