/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Denis Imeri
 */
public class TestGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TestGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbText = new javax.swing.JLabel();
        tfInputOutput = new javax.swing.JTextField();
        btCalculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test Fenster");

        lbText.setBackground(new java.awt.Color(255, 255, 0));
        lbText.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        lbText.setForeground(new java.awt.Color(255, 0, 0));
        lbText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbText.setText("HALLO LOL");
        lbText.setOpaque(true);
        getContentPane().add(lbText, java.awt.BorderLayout.PAGE_START);

        tfInputOutput.setColumns(30);
        tfInputOutput.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfInputOutput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfInputOutput.setPreferredSize(new java.awt.Dimension(434, 90));
        tfInputOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInputOutputActionPerformed(evt);
            }
        });
        getContentPane().add(tfInputOutput, java.awt.BorderLayout.CENTER);

        btCalculate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btCalculate.setText("Berechne");
        btCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCalculate(evt);
            }
        });
        getContentPane().add(btCalculate, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfInputOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInputOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInputOutputActionPerformed

    private void onCalculate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCalculate
        // TODO add your handling code here:
        String input = tfInputOutput.getText();
        int value = Integer.parseInt(input);
        value++;
        tfInputOutput.setText(value+"");
    }//GEN-LAST:event_onCalculate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalculate;
    private javax.swing.JLabel lbText;
    private javax.swing.JTextField tfInputOutput;
    // End of variables declaration//GEN-END:variables
}
