/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Denis Imeri
 */
public class StationListGUI extends javax.swing.JFrame {
    
    private DefaultListModel<String> stations = new DefaultListModel<>();

    /**
     * Creates new form StationListGUI
     */
    public StationListGUI() {
        initComponents();
        liStations.setModel(stations);
        this.setLocationRelativeTo(null);
        this.setSize(400, 650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btInit = new javax.swing.JButton();
        spStations = new javax.swing.JScrollPane();
        liStations = new javax.swing.JList<>();
        paAction = new javax.swing.JPanel();
        tfAction = new javax.swing.JTextField();
        btInsert = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        btShuffle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btInit.setText("init");
        btInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onInitList(evt);
            }
        });
        getContentPane().add(btInit, java.awt.BorderLayout.NORTH);

        liStations.setBorder(javax.swing.BorderFactory.createTitledBorder("List of Stations"));
        liStations.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spStations.setViewportView(liStations);

        getContentPane().add(spStations, java.awt.BorderLayout.CENTER);

        paAction.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));
        paAction.setLayout(new java.awt.GridLayout(5, 1, 0, 2));
        paAction.add(tfAction);

        btInsert.setText("Insert");
        btInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onInsert(evt);
            }
        });
        paAction.add(btInsert);

        btRemove.setText("Remove");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRemove(evt);
            }
        });
        paAction.add(btRemove);

        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClear(evt);
            }
        });
        paAction.add(btClear);

        btShuffle.setText("Shuffle");
        btShuffle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onShuffle(evt);
            }
        });
        paAction.add(btShuffle);

        getContentPane().add(paAction, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onInitList(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onInitList
        stations.clear();
        stations.addElement("ATV");
        stations.addElement("ORF1");
        stations.addElement("ORF2");
        stations.addElement("ARD");
        stations.addElement("PULS4");
        stations.addElement("PROSIEBEN");
    }//GEN-LAST:event_onInitList

    private void onInsert(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onInsert
        String text = tfAction.getText().toUpperCase();
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(this, "The text field is empty");
            return;
        }
        
        if(stations.contains(text)){
            JOptionPane.showMessageDialog(this, "This station is already in the list");
            return;
        }
        
        int selected = liStations.getSelectedIndex();
        if(selected==-1){
            stations.addElement(text);
            return;
        }
        stations.add(selected, text);
    }//GEN-LAST:event_onInsert

    private void onRemove(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRemove
        int[] selected = liStations.getSelectedIndices();
        if(selected.length==0){
            JOptionPane.showMessageDialog(this, "You have not selected any stations to remove");
            return;
        }
        
        int count = 0;
        for(int index : selected){
            stations.remove(index-count);
            count++;
        }
    }//GEN-LAST:event_onRemove

    private void onClear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClear
        stations.clear();
    }//GEN-LAST:event_onClear

    private void onShuffle(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onShuffle
        List<String> temp = new ArrayList(Arrays.asList(stations.toArray()));
        Collections.shuffle(temp);
        stations.clear();
        for(String item : temp){
            stations.addElement(item);
        }
    }//GEN-LAST:event_onShuffle

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StationListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StationListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StationListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StationListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StationListGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btInit;
    private javax.swing.JButton btInsert;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btShuffle;
    private javax.swing.JList<String> liStations;
    private javax.swing.JPanel paAction;
    private javax.swing.JScrollPane spStations;
    private javax.swing.JTextField tfAction;
    // End of variables declaration//GEN-END:variables
}
