/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Denis Imeri
 */
public class NamensListeGUI extends javax.swing.JFrame {

    public List<String> names = new LinkedList<>();

    /**
     * Creates new form NamensListeGUI
     */
    public NamensListeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paName = new javax.swing.JPanel();
        tfName = new javax.swing.JTextField();
        btInsert = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        paContent = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        tfDisplayN = new javax.swing.JTextField();
        btUp = new javax.swing.JButton();
        lbPos = new javax.swing.JLabel();
        tfDisplayP = new javax.swing.JTextField();
        btDown = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        paName.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));
        paName.setLayout(new java.awt.GridLayout(3, 1, 5, 5));

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });
        paName.add(tfName);

        btInsert.setText("einfügen");
        btInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onEinfuegen(evt);
            }
        });
        paName.add(btInsert);

        btDelete.setText("löschen");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLoeschen(evt);
            }
        });
        paName.add(btDelete);

        getContentPane().add(paName);

        paContent.setBorder(javax.swing.BorderFactory.createTitledBorder("Listeninhalt"));
        paContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        paContent.setLayout(new java.awt.GridLayout(2, 3, 5, 5));

        lbName.setText("Name:");
        paContent.add(lbName);

        tfDisplayN.setEditable(false);
        paContent.add(tfDisplayN);

        btUp.setText("/\\");
            btUp.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    onListeUp(evt);
                }
            });
            paContent.add(btUp);

            lbPos.setText("Position:");
            paContent.add(lbPos);

            tfDisplayP.setEditable(false);
            paContent.add(tfDisplayP);

            btDown.setText("\\/");
            btDown.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    onListeDown(evt);
                }
            });
            paContent.add(btDown);

            getContentPane().add(paContent);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void onEinfuegen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onEinfuegen
        String name = tfName.getText();
        if (names.contains(name)) {
            JOptionPane.showMessageDialog(this, "This name is already in this List");
            return;
        }
        names.add(name);
        Collections.sort(names);
        if (tfDisplayN.getText().isEmpty()) {
            setText(0);
        }
        else {
            int index = names.indexOf(tfDisplayN.getText()) + 1;
            tfDisplayP.setText(String.format("%d von %d", index, names.size()));
        }
    }//GEN-LAST:event_onEinfuegen

    private void onLoeschen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLoeschen
        String name = tfName.getText();
        int index = names.indexOf(name);
        if(index == -1){
            JOptionPane.showMessageDialog(this, "This name is not on the List");
        }
        else {
            if(tfDisplayN.getText().equals(names.get(index))) {
                System.out.println(names.get(index));
                names.remove(index);
                setText(0);
                return;
            }
            names.remove(index);
            String curName = tfDisplayN.getText();
            int curIndex = names.indexOf(curName);
            setPos(curIndex);
        }
        
    }//GEN-LAST:event_onLoeschen

    public void setText(int index) {
        tfDisplayN.setText(names.get(index));
        tfDisplayP.setText(String.format("%d von %d", index+1, names.size()));
    }
    
    public void setPos(int index) {
        tfDisplayP.setText(String.format("%d von %d", index+1, names.size()));
    }
    private void onListeUp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onListeUp
        int index = names.indexOf(tfDisplayN.getText())+1;
        if(index == names.size()){
            setText(0);
            return;
        }
        setText(index);
    }//GEN-LAST:event_onListeUp

    private void onListeDown(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onListeDown
        int index = names.indexOf(tfDisplayN.getText())+1;
        if(index == -1){
            setText(names.size()-1);
            return;
        }
        setText(index);
    }//GEN-LAST:event_onListeDown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NamensListeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NamensListeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NamensListeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NamensListeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NamensListeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelete;
    private javax.swing.JToggleButton btDown;
    private javax.swing.JButton btInsert;
    private javax.swing.JButton btUp;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPos;
    private javax.swing.JPanel paContent;
    private javax.swing.JPanel paName;
    private javax.swing.JTextField tfDisplayN;
    private javax.swing.JTextField tfDisplayP;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
