/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.MinMaxBL;
import java.util.Random;

/**
 *
 * @author Denis Imeri
 */
public class MinMaxGUI extends javax.swing.JFrame {

    /**
     * Creates new form MinMaxGUI
     */
    public MinMaxGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spOutput = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        btCalculate = new javax.swing.JButton();
        paInput = new javax.swing.JPanel();
        lbBig = new javax.swing.JLabel();
        tfBig = new javax.swing.JTextField();
        btSmall = new javax.swing.JLabel();
        tfSmall = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MinMax");
        setPreferredSize(new java.awt.Dimension(500, 500));

        spOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("Zahlenfeld"));

        taOutput.setColumns(20);
        taOutput.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 14)); // NOI18N
        taOutput.setRows(5);
        spOutput.setViewportView(taOutput);

        getContentPane().add(spOutput, java.awt.BorderLayout.CENTER);

        btCalculate.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 14)); // NOI18N
        btCalculate.setText("CALCULATE");
        btCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });
        getContentPane().add(btCalculate, java.awt.BorderLayout.PAGE_START);

        paInput.setLayout(new java.awt.GridLayout(2, 2));

        lbBig.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 14)); // NOI18N
        lbBig.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbBig.setText("Größter Wert: ");
        paInput.add(lbBig);

        tfBig.setEditable(false);
        tfBig.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 14)); // NOI18N
        tfBig.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfBig.setText("999");
        paInput.add(tfBig);

        btSmall.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 14)); // NOI18N
        btSmall.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btSmall.setText("Kleinster Wert: ");
        paInput.add(btSmall);

        tfSmall.setEditable(false);
        tfSmall.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 14)); // NOI18N
        tfSmall.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfSmall.setText("0");
        paInput.add(tfSmall);

        getContentPane().add(paInput, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClick
        taOutput.setText("");
        Random rand = new Random();
        int[] feld = new int[100];
        for (int i = 1; i < 101; i++) {   
            feld[i-1] = rand.nextInt(1000);
            taOutput.append(String.format("%3d, ", feld[i-1]));
            if(i%10==0){
                taOutput.append(String.format("\n"));
            }
        }
        MinMaxBL bl = new MinMaxBL(feld);
        bl.berechneMinMax();
        tfBig.setText(String.format("%d", bl.getMax()));
        tfSmall.setText(String.format("%d", bl.getMin()));
    }//GEN-LAST:event_onClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinMaxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinMaxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinMaxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinMaxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinMaxGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalculate;
    private javax.swing.JLabel btSmall;
    private javax.swing.JLabel lbBig;
    private javax.swing.JPanel paInput;
    private javax.swing.JScrollPane spOutput;
    private javax.swing.JTextArea taOutput;
    private javax.swing.JTextField tfBig;
    private javax.swing.JTextField tfSmall;
    // End of variables declaration//GEN-END:variables
}
