/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.CalenderBL;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Denis Imeri
 */
public class CalenderGUI extends javax.swing.JFrame {

    /*
     * Creates new form CalenderGUI
     */
    public CalenderGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spOut = new javax.swing.JScrollPane();
        epOut = new javax.swing.JEditorPane();
        paTop = new javax.swing.JPanel();
        lbMonat = new javax.swing.JLabel();
        tfMonat = new javax.swing.JTextField();
        btMonat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btCreateT = new javax.swing.JButton();
        btDeleteT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));

        epOut.setContentType("text/html"); // NOI18N
        spOut.setViewportView(epOut);

        getContentPane().add(spOut, java.awt.BorderLayout.CENTER);

        paTop.setLayout(new java.awt.GridLayout(1, 0));

        lbMonat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMonat.setText("Monat:");
        paTop.add(lbMonat);
        paTop.add(tfMonat);

        btMonat.setText("erzeuge");
        btMonat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onGenerateDaysOfMonth(evt);
            }
        });
        paTop.add(btMonat);

        getContentPane().add(paTop, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btCreateT.setText("Termine erzeugen");
        btCreateT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onGenerateEvents(evt);
            }
        });
        jPanel3.add(btCreateT);

        btDeleteT.setText("Termin löschen");
        btDeleteT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRemoveEvents(evt);
            }
        });
        jPanel3.add(btDeleteT);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onGenerateDaysOfMonth(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onGenerateDaysOfMonth
        btCreateT.setEnabled(true);
        try{
            String input = tfMonat.getText().trim();
            
            if(input.isEmpty()){
                JOptionPane.showMessageDialog(this, "Sie haben nichts eingegeben");
            }
            String first = input.substring(0, 1).toUpperCase();
            String last = input.substring(1);
            input = first + last;
            
            String output = CalenderBL.generateDaysOfMonth(input);
            epOut.setText(output);
        }catch(DateTimeParseException e){
            JOptionPane.showMessageDialog(this, "Sie haben einen falschen Monat eingegeben");
        }
        
    }//GEN-LAST:event_onGenerateDaysOfMonth

    private void onGenerateEvents(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onGenerateEvents
        String text = epOut.getText();
        btCreateT.setEnabled(false);
        epOut.setText(CalenderBL.generateEvents("feb", text));
    }//GEN-LAST:event_onGenerateEvents

    private void onRemoveEvents(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRemoveEvents
        try {
            int day = Integer.parseInt(JOptionPane.showInputDialog("Gib einen Tag ein"));
            epOut.setText(CalenderBL.removeEvent(day, epOut.getText()));
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Du hast keinen richtigen Tag eingegeben");
        }
    }//GEN-LAST:event_onRemoveEvents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalenderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalenderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalenderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalenderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalenderGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreateT;
    private javax.swing.JButton btDeleteT;
    private javax.swing.JButton btMonat;
    private javax.swing.JEditorPane epOut;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbMonat;
    private javax.swing.JPanel paTop;
    private javax.swing.JScrollPane spOut;
    private javax.swing.JTextField tfMonat;
    // End of variables declaration//GEN-END:variables
}
