/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;

/**
 *
 * @author crether
 */
public class Main extends javax.swing.JFrame {

    private Thread localThread;
    public static final int HEIGHT = 300;
    public static final int WIDTH = 600;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        localPanel = new TimePanel();
        pa2 = new TimePanel();
        pa3 = new TimePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                onResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                onShown(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        localPanel.setLayout(new javax.swing.BoxLayout(localPanel, javax.swing.BoxLayout.X_AXIS));
        getContentPane().add(localPanel);

        pa2.setLayout(new javax.swing.BoxLayout(pa2, javax.swing.BoxLayout.X_AXIS));
        getContentPane().add(pa2);

        pa3.setLayout(new javax.swing.BoxLayout(pa3, javax.swing.BoxLayout.X_AXIS));
        getContentPane().add(pa3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_onShown
        TimePanel local = (TimePanel) localPanel;
        local.init(true);
//        this.setPreferredSize(new Dimension(WIDTH, HEIGHT));
//        this.setMaximumSize(new Dimension(WIDTH, HEIGHT));
        this.setMinimumSize(new Dimension(WIDTH, HEIGHT));
        localThread = new Thread((Runnable) local);
        localThread.start();
    }//GEN-LAST:event_onShown

    private void onResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_onResized
        TimePanel local = (TimePanel) localPanel;
        local.resize();
    }//GEN-LAST:event_onResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel localPanel;
    private javax.swing.JPanel pa2;
    private javax.swing.JPanel pa3;
    // End of variables declaration//GEN-END:variables
}
