/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.EulerBL;

/**
 *
 * @author Denis Imeri
 */
public class EulerGUI extends javax.swing.JFrame {

    /**
     * Creates new form EulerGUI
     */
    public EulerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paCheckboxes = new javax.swing.JPanel();
        cb1 = new javax.swing.JCheckBox();
        cb9 = new javax.swing.JCheckBox();
        cb20 = new javax.swing.JCheckBox();
        cb24 = new javax.swing.JCheckBox();
        cbSelf = new javax.swing.JCheckBox();
        btCalculate = new javax.swing.JButton();
        spOut = new javax.swing.JScrollPane();
        taOut = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 300));

        paCheckboxes.setLayout(new java.awt.GridLayout(5, 1));

        cb1.setText("1 - Multiplies of 3 and 5");
        paCheckboxes.add(cb1);

        cb9.setText("9 - Special Pythagorean Triplet");
        paCheckboxes.add(cb9);

        cb20.setText("20 - Factorial Digit Sum");
        paCheckboxes.add(cb20);

        cb24.setText("24 - Lexicographic Permutations (takes a long time)");
        cb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb24ActionPerformed(evt);
            }
        });
        paCheckboxes.add(cb24);

        cbSelf.setText("52 - Permuted multiples");
        paCheckboxes.add(cbSelf);

        getContentPane().add(paCheckboxes, java.awt.BorderLayout.PAGE_START);

        btCalculate.setText("Calculate");
        btCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCalculate(evt);
            }
        });
        getContentPane().add(btCalculate, java.awt.BorderLayout.CENTER);

        taOut.setColumns(20);
        taOut.setRows(5);
        spOut.setViewportView(taOut);

        getContentPane().add(spOut, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb24ActionPerformed

    private void onCalculate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCalculate
        taOut.setText("");
        if(cb1.isSelected()){
            int pb1 = EulerBL.problem1();
            String str = String.format("Problem 1 (Multiplies of 3 and 5):\n"
                    + "%d\n"
                    + "-----------------------------------\n", pb1); 
            taOut.append(str);
        }
        if(cb9.isSelected()){
            int pb9 = EulerBL.problem9();
            String str = String.format("Problem 9 (Special Pythagorean triplet):\n"
                    + "%d\n"
                    + "-----------------------------------\n", pb9); 
            taOut.append(str);
        }
        if(cb20.isSelected()){
            int pb20 = EulerBL.problem20();
            String str = String.format("Problem 20 (Factorial Digit Sum):\n"
                    + "%d\n"
                    + "-----------------------------------\n", pb20); 
            taOut.append(str);
        }
        if(cb24.isSelected()){
            long pb24 = EulerBL.problem24();
            String str = String.format("Problem 24 (Lexicographic permutations):\n"
                    + "%d\n"
                    + "-----------------------------------\n", pb24); 
            taOut.append(str);
        }
        if(cbSelf.isSelected()){
            int pb52 = EulerBL.problem52();
            String str = String.format("Problem 52 (Permuted multiples):\n"
                    + "%d\n"
                    + "-----------------------------------\n", pb52); 
            taOut.append(str);
        }
    }//GEN-LAST:event_onCalculate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EulerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalculate;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb20;
    private javax.swing.JCheckBox cb24;
    private javax.swing.JCheckBox cb9;
    private javax.swing.JCheckBox cbSelf;
    private javax.swing.JPanel paCheckboxes;
    private javax.swing.JScrollPane spOut;
    private javax.swing.JTextArea taOut;
    // End of variables declaration//GEN-END:variables
}
