/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.FFItem;
import bl.ItemListModel;

/**
 *
 * @author Denis Imeri
 */
public class FFGui extends javax.swing.JFrame {
    
    private ItemListModel items = new ItemListModel();

    /**
     * Creates new form FFGui
     */
    public FFGui() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        paBottom = new javax.swing.JPanel();
        spEnergy = new javax.swing.JScrollPane();
        taEnergy = new javax.swing.JTextArea();
        spSaturates = new javax.swing.JScrollPane();
        taSaturates = new javax.swing.JTextArea();
        spSugars = new javax.swing.JScrollPane();
        taSugars = new javax.swing.JTextArea();
        spSalt = new javax.swing.JScrollPane();
        taSalt = new javax.swing.JTextArea();
        spProducts = new javax.swing.JScrollPane();
        liProducts = new javax.swing.JList<>();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        paBottom.setBorder(javax.swing.BorderFactory.createTitledBorder("Meal's Recommended Allowance [%]"));
        paBottom.setLayout(new java.awt.GridLayout(1, 0));

        taEnergy.setColumns(20);
        taEnergy.setRows(5);
        spEnergy.setViewportView(taEnergy);

        paBottom.add(spEnergy);

        taSaturates.setColumns(20);
        taSaturates.setRows(5);
        spSaturates.setViewportView(taSaturates);

        paBottom.add(spSaturates);

        taSugars.setColumns(20);
        taSugars.setRows(5);
        spSugars.setViewportView(taSugars);

        paBottom.add(spSugars);

        taSalt.setColumns(20);
        taSalt.setRows(5);
        spSalt.setViewportView(taSalt);

        paBottom.add(spSalt);

        getContentPane().add(paBottom, java.awt.BorderLayout.PAGE_END);

        liProducts.setBorder(javax.swing.BorderFactory.createTitledBorder("Product List"));
        spProducts.setViewportView(liProducts);

        getContentPane().add(spProducts, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FFGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FFGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FFGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FFGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FFGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JList<FFItem> liProducts;
    private javax.swing.JPanel paBottom;
    private javax.swing.JScrollPane spEnergy;
    private javax.swing.JScrollPane spProducts;
    private javax.swing.JScrollPane spSalt;
    private javax.swing.JScrollPane spSaturates;
    private javax.swing.JScrollPane spSugars;
    private javax.swing.JTextArea taEnergy;
    private javax.swing.JTextArea taSalt;
    private javax.swing.JTextArea taSaturates;
    private javax.swing.JTextArea taSugars;
    // End of variables declaration//GEN-END:variables
}
