/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.Equation;

/**
 *
 * @author Denis Imeri
 */
public class EquationGUI extends javax.swing.JFrame {

    /**
     * Creates new form EquationGUI
     */
    public EquationGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btX2 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        btX = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        btPlus = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btIs0 = new javax.swing.JButton();
        btCLR = new javax.swing.JButton();
        btMinus = new javax.swing.JButton();
        spOutput = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 4));

        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDigit(evt);
            }
        });
        jPanel1.add(bt7);

        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDigit(evt);
            }
        });
        jPanel1.add(bt8);

        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDigit(evt);
            }
        });
        jPanel1.add(bt9);

        btX2.setText("x²");
        btX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onX(evt);
            }
        });
        jPanel1.add(btX2);

        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDigit(evt);
            }
        });
        jPanel1.add(bt4);

        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDigit(evt);
            }
        });
        jPanel1.add(bt5);

        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDigit(evt);
            }
        });
        jPanel1.add(bt6);

        btX.setText("x");
        btX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onX(evt);
            }
        });
        jPanel1.add(btX);

        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDigit(evt);
            }
        });
        jPanel1.add(bt1);

        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDigit(evt);
            }
        });
        jPanel1.add(bt2);

        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDigit(evt);
            }
        });
        jPanel1.add(bt3);

        btPlus.setText("+");
        btPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPlusMinus(evt);
            }
        });
        jPanel1.add(btPlus);

        bt0.setText("0");
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDigit(evt);
            }
        });
        jPanel1.add(bt0);

        btIs0.setText("=0");
        btIs0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCalculate(evt);
            }
        });
        jPanel1.add(btIs0);

        btCLR.setText("CLR");
        btCLR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClear(evt);
            }
        });
        jPanel1.add(btCLR);

        btMinus.setText("-");
        btMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPlusMinus(evt);
            }
        });
        jPanel1.add(btMinus);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        taOutput.setColumns(20);
        taOutput.setRows(5);
        spOutput.setViewportView(taOutput);

        getContentPane().add(spOutput, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onDigit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDigit
        String num = evt.getActionCommand();
        if(num == "0"){
            String input = taOutput.getText();
            if(!(input.length() == 0)){

            }
        }
        taOutput.append(num);
    }//GEN-LAST:event_onDigit

    private void onCalculate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCalculate
        String num = evt.getActionCommand();
        String text = taOutput.getText();
        Equation eq = new Equation();
        int[] splitted = eq.parse(text);
        taOutput.setText(String.format("%d %d %d", splitted[0] + splitted[1] + splitted[2]));
        taOutput.append(num);
    }//GEN-LAST:event_onCalculate

    private void onClear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClear
        taOutput.setText("");
    }//GEN-LAST:event_onClear

    private void onPlusMinus(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPlusMinus
        // TODO add your handling code here:
        
        String num = evt.getActionCommand();
        taOutput.append(num);
    }//GEN-LAST:event_onPlusMinus

    private void onX(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onX
        // TODO add your handling code here:
        String num = evt.getActionCommand();
        taOutput.append(num);
    }//GEN-LAST:event_onX

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EquationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EquationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EquationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EquationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EquationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btCLR;
    private javax.swing.JButton btIs0;
    private javax.swing.JButton btMinus;
    private javax.swing.JButton btPlus;
    private javax.swing.JButton btX;
    private javax.swing.JButton btX2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane spOutput;
    private javax.swing.JTextArea taOutput;
    // End of variables declaration//GEN-END:variables
}
