/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.NumberFormatter;
import javax.swing.JOptionPane;

/**
 *q
 * @author Denis Imeri
 */
public class FormatterGUI extends javax.swing.JFrame {

    /**
     * Creates new form FormatterGUI
     */
    public FormatterGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        btFormat = new javax.swing.JButton();
        spBottom = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        paTop = new javax.swing.JPanel();
        lbNumber = new javax.swing.JLabel();
        tfNumber = new javax.swing.JTextField();
        cbTrennzeichen = new javax.swing.JCheckBox();
        lbFormat = new javax.swing.JLabel();
        tfFormat = new javax.swing.JTextField();
        cbRight = new javax.swing.JCheckBox();
        lbFill = new javax.swing.JLabel();
        tfFill = new javax.swing.JTextField();

        jCheckBox3.setText("jCheckBox3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btFormat.setText("formatieren");
        btFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFormat(evt);
            }
        });
        getContentPane().add(btFormat, java.awt.BorderLayout.CENTER);

        taOutput.setColumns(20);
        taOutput.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        taOutput.setRows(3);
        spBottom.setViewportView(taOutput);

        getContentPane().add(spBottom, java.awt.BorderLayout.PAGE_END);

        paTop.setFocusable(false);
        paTop.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        paTop.setLayout(new java.awt.GridLayout(3, 3));

        lbNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNumber.setText("Eingabezahl ");
        paTop.add(lbNumber);

        tfNumber.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paTop.add(tfNumber);

        cbTrennzeichen.setText("Trennzeichen");
        paTop.add(cbTrennzeichen);

        lbFormat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbFormat.setText("Format ");
        paTop.add(lbFormat);

        tfFormat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paTop.add(tfFormat);

        cbRight.setText("rechtsbündig");
        paTop.add(cbRight);

        lbFill.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbFill.setText("Füllzeichen ");
        paTop.add(lbFill);

        tfFill.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfFill.setText("*");
        paTop.add(tfFill);

        getContentPane().add(paTop, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onFormat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onFormat
        String input = tfNumber.getText().trim().replace(",", ".");
        if(input.isEmpty()){
            JOptionPane.showMessageDialog(this, "Sie haben keine Eingabezahl eingegeben");
            return;
        }
        
        double doubleInput = 0;
        try{
            doubleInput = Double.valueOf(input);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Sie haben keine Zahl eingegeben");
        }
            
        String format = tfFormat.getText().trim();
        if(format.isEmpty()){
            JOptionPane.showMessageDialog(this, "Es ist kein Format spezifiziert");
            return;
        }

        String strFillChar = tfFill.getText().trim();
        if(strFillChar.isEmpty()){
            JOptionPane.showMessageDialog(this, "Sie haben keinen Füllcharakter eingegeben");
            return;
        }
        char fillChar = strFillChar.charAt(0);
        
        String formatted = "";
        try {
            formatted = NumberFormatter.format(doubleInput, format, fillChar, cbRight.isSelected(), cbTrennzeichen.isSelected());
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getCause());
        }
        
        String output = NumberFormatter.getDigitLine(formatted.length()) + formatted;
        taOutput.setText(output);
    }//GEN-LAST:event_onFormat

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormatterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormatterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormatterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormatterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormatterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFormat;
    private javax.swing.JCheckBox cbRight;
    private javax.swing.JCheckBox cbTrennzeichen;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel lbFill;
    private javax.swing.JLabel lbFormat;
    private javax.swing.JLabel lbNumber;
    private javax.swing.JPanel paTop;
    private javax.swing.JScrollPane spBottom;
    private javax.swing.JTextArea taOutput;
    private javax.swing.JTextField tfFill;
    private javax.swing.JTextField tfFormat;
    private javax.swing.JTextField tfNumber;
    // End of variables declaration//GEN-END:variables
}
